language: node_js
node_js: stable
branches:
  only:
  - pages
cache:
  directories:
  - node_modules
before_install:
- npm install -g hexo-cli
install:
- npm i
script:
- hexo clean
- hexo generate
- pwd
- ls -al
- ls -al ./public/
- cat ./public/index.html
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com/bluemiix/bluemiix.github.io.git
  master